name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '16', '18' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Test package_info
        run: npm run test:package_info

      - name: Build
        run: npm run build

      - name: Test
        run: npm run coverage
